backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Strony"
    files:
      - file: "src/pages/index.md"
        label: "Strona główna"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
      - file: "src/pages/o-kancelarii/index.md"
        label: "O kancelarii"
        name: "o-kancelarii"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "simple-page"}
          - {label: "Tytuł strony", name: "title", widget: "string"}
          - {label: "Treść strony", name: "body", widget: "markdown"}
      - file: "src/pages/porady-prawne-online/index.md"
        label: "Porady prawne online"
        name: "porady-prawne-online"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "simple-page"}
          - {label: "Tytuł strony", name: "title", widget: "string"}
          - {label: "Treść strony", name: "body", widget: "markdown"}
      - file: "src/pages/kontakt/index.md"
        label: "Kontakt"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "simple-page"}
          - {label: "Tytuł strony", name: "title", widget: "string"}
          - {label: "Numer telefonu", name: "phone", widget: "string"}
          - {label: "Adres email", name: "mail", widget: "string"}
          - label: "Siedziba kancelarii"
            name: "address"
            widget: "list"
            fields:
              - {label: "Adres", name: addressName, widget: string}
              - {label: "Link do mapy (embed google maps)", name: mapSrc, widget: string}
          - {label: "Treść strony", name: "body", widget: "markdown"}

  - name: "specializations"
    label: "Specjalizacje"
    folder: "src/pages/specjalizacje"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "specialization-page"}
      - {label: "Nazwa specjalizacji", name: "title", widget: "string"}
      - {label: "Numer w kolejności specjalizacji", name: "order", widget: "number", min: 1, valueType: "int"}
      - {label: "Opis", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Tytuł artykułu", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Treść artykułu", name: "body", widget: "markdown"}