backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Tytuł artykułu", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Treść artykułu", name: "body", widget: "markdown"}

  - label: "Specjalizacje"
    name: "specializations"
    folder: "src/pages/specializations"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "specialization-page"}
      - {label: "Nazwa specjalizacji", name: "title", widget: "string"}
      - {label: "Opis", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Strona główna"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/o-kancelarii/index.md"
        label: "O kancelarii"
        name: "o-kancelarii"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "simple-page"}
          - {label: "Tytuł strony", name: "title", widget: "string"}
          - {label: "Treść strony", name: "body", widget: "markdown"}
      - file: "src/pages/porady-prawne-online/index.md"
        label: "Porady prawne online"
        name: "porady-prawne-online"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "simple-page"}
          - {label: "Tytuł strony", name: "title", widget: "string"}
          - {label: "Treść strony", name: "body", widget: "markdown"}
      - file: "src/pages/kontakt/index.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "simple-page"}
          - {label: "Tytuł strony", name: "title", widget: "string"}
          - {label: "Treść strony", name: "body", widget: "markdown"}
          - {label: "Number telefonu", name: "phone", widget: "string"}
          - {label: "Adres email", name: "mail", widget: "string"}